name: Build Binaries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
            output: file-merger-linux-amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
            output: file-merger-darwin-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: ".exe"
            output: file-merger-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o ${{ matrix.output }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
          retention-days: 5

  release:
    name: Create Release
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: find . -type f | sort

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto-build-${{ github.run_number }}
          name: Automated Build ${{ github.run_number }}
          draft: false
          prerelease: true
          files: |
            ./file-merger-linux-amd64
            ./file-merger-darwin-amd64
            ./file-merger-windows-amd64.exe
