name: Build Binaries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output: file-merger-linux-amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            output: file-merger-darwin-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            output: file-merger-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v -o ${{ matrix.output }} .
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
          retention-days: 5

  release:
    name: Create Release
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Create Release Directory
        run: mkdir -p release

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: file-merger-linux-amd64
          path: release

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: file-merger-darwin-amd64
          path: release

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: file-merger-windows-amd64.exe
          path: release

      - name: Display structure of downloaded files
        run: |
          ls -la release/
          chmod +x release/file-merger-linux-amd64
          chmod +x release/file-merger-darwin-amd64
          # Windows .exe 文件不需要设置可执行权限

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto-build-${{ github.run_number }}
          name: Automated Build ${{ github.run_number }}
          draft: false
          prerelease: true
          files: |
            release/file-merger-linux-amd64
            release/file-merger-darwin-amd64
            release/file-merger-windows-amd64.exe
